src/Entity/Chambre.php
<?php

namespace App\Entity;



use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ChambreRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: ChambreRepository::class)]
class Chambre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    private ?string $description_courte = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description_longue = null;

    #[ORM\Column(length: 255)]
    private ?string $photo = null;

    #[ORM\Column]
    private ?int $prix_journalier = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\OneToMany(mappedBy: 'chambre', targetEntity: Commande::class, orphanRemoval: true)]
    private $commande;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescriptionCourte(): ?string
    {
        return $this->description_courte;
    }

    public function setDescriptionCourte(string $description_courte): self
    {
        $this->description_courte = $description_courte;

        return $this;
    }

    public function getDescriptionLongue(): ?string
    {
        return $this->description_longue;
    }

    public function setDescriptionLongue(string $description_longue): self
    {
        $this->description_longue = $description_longue;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPrixJournalier(): ?int
    {
        return $this->prix_journalier;
    }

    public function setPrixJournalier(int $prix_journalier): self
    {
        $this->prix_journalier = $prix_journalier;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commande;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commande->contains($commande)) {
            $this->commande->add($commande);
            $commande->setChambre($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commande->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getChambre() === $this) {
                $commande->setChambre(null);
            }
        }

        return $this;
    }
    public function ___toString()
    {
        return (string) $this->getCommandes();
    }
}

src/Controller/HotelController.php
<?php

namespace App\Controller;

use App\Entity\Chambre;
use App\Entity\Commande;
use App\Repository\ChambreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class HotelController extends AbstractController
{
    #[Route('/', name: 'root')]
    public function root()
    {
        // redirige simplement vers la page d'accueil
        return $this->redirectToRoute('app_hotel');
    }
    #[Route('/hotel', name: 'app_hotel')]
    public function index(): Response
    {
        return $this->render('hotel/index.html.twig', [
            'controller_name' => 'HotelController'
        ]);
    }
    #[Route('/hotel/chambre', name: 'hotel_chambre')]
    public function chambre(ChambreRepository $repo): Response
    {
        $chambre = $repo->findAll();
        return $this->render('hotel/chambre.html.twig', [
            'chambre' => $chambre
        ]);
    }
    #[Route('/hotel/restaurant', name: 'hotel_restaurant')]
    public function restaurant(): Response
    {
        
        return $this->render('hotel/restaurant.html.twig', [
            'restaurant' => 'Notre restaurant',
        ]);
    }
    #[Route('/hotel/spa', name: 'hotel_spa')]
    public function spa(): Response
    {
        return $this->render('hotel/spa.html.twig', [
            'bien_être' => 'Présentation de notre Spa',
        ]);
    }
    #[Route('/hotel/propos', name: 'hotel_propos')]
    public function propos(): Response
    {
        return $this->render('hotel/propos.html.twig', [
            'controller_name' => 'HotelController',
        ]);
    }
    

   
}


   

templates/hotel/chambre.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HotelController!
{% endblock %}

{% block body %}
<body style= "background-color:#D7CCC8">
<h1 class="text-center">Nos chambres </h1>
<section>

	<div class="col-md-3 m-5 d-inline-block">
		<div style="background-color:#C5B7C7" class="card" style="width: 18rem;">
			
				<div class="card-body ">
					<h5 class="card-title rounded shadow-sm text-center">Chambre Classique</h5>
                    <img src="https://images.unsplash.com/photo-1566665797739-1674de7a421a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDF8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60" width="550px" height="250px"  class="card-img-top">
                    <h6 class="card-text m-3">Chambre pour une personne</h6>
					<p class="card-text">Chambre pour une personne, literie haut de gamme, lit 160, 10 m2, salle de bain private équipée d'une douche. La chambre classique allie confort et équipements modernes, idéal pour un court séjour.  Ces chambres ont toutes été relookées par notre designer.</p>
					<h5 class="card-text">99.00 €</h5>
					<a href="" class="btn btn-secondary ">Réserver</a>
				</div>
		</div>
	</div>

	<div  class="col-md-3 m-4 d-inline-block">
		<div style="background-color:#C5B7C7" class="card" style="width: 18rem;">
			
				<div class="card-body">
					<h5 class="card-title rounded shadow-sm text-center">Chambre Confort</h5>
                    <img src="https://images.unsplash.com/photo-1618773928121-c32242e63f39?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop"width="550px" height="250px"   class="card-img-top">
                    <h6 class="card-text m-3">Chambre pour deux personnes</h6>
					<p class="card-text ">Chambres doubles, entièrement rénovées et décorées individuellement. Nous avons donné libre cours à l'imagination des décorateurs quant à la création d'une véritable ambiance parisienne. Les toutes nouvelles salles de bains sont d'un blanc immaculé.</p>
					<h5 class="card-text">120.00 €</h5>
					<a href="" class="btn btn-secondary m-6">Réserver</a>
				</div>
		</div>
	</div>

	<div class="col-md-3 m-5 d-inline-block">
		<div style="background-color:#C5B7C7" class="card" style="width: 18rem;">
			
				<div class="card-body">
					<h5 class="card-title rounded shadow-sm text-center">Suite</h5>
                    <img src="https://images.unsplash.com/photo-1562438668-bcf0ca6578f0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDd8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop" width="550px" height="250px" class="card-img-top ">
                    <h6 class="card-text m-3 ">Chambre pour deux personnes</h6>
					<p class="card-text">Chambres doubles, entièrement rénovées et décorées individuellement. Nous avons donné libre cours à l'imagination des décorateurs quant à la création d'une véritable ambiance parisienne. Les toutes nouvelles salles de bains sont d'un blanc immaculé.</p>
					<h5 class="card-text font-weight-bold">210.00 €</h5>
					<a href="" class="btn btn-secondary m-6">Réserver</a>
				</div>
		</div>
	</div>

	
	
	

</body>


{% endblock %}

templates/hotel/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HotelController!
{% endblock %}

{% block body %}
<body height="2000px"style= "background-color:#D7CCC8">
  <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators m-3">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner  align-textcenter">
      <div class="carousel-item active">
        <img src="	https://assets-global.website-files.com/5c6d6c45eaa55f57c6367749/624b4890bd1805cb55fd0784_10%20key%20bg.jpeg" class="d-block w-100"  alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>Notre Réception</h5>
          <p>Notre personnel est à votre écoute</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="	https://www.hotel-lancaster.com/_novaimg/galleria/1443560.jpg" width="480px" height="650px" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>Notre restaurant</h5>
          <p>Notre chef étoilé vous réserve les meilleurs plats.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="	https://staycation.twic.pics/v1/resize=1440/image:pictures/production/552e936ae9b712d34af00d9860378083.jpg" width="480px" height="650px" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>Notre spa</h5>
          <p>Notre personnel vous propose plusieurs formules de détente.</p>
        </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<div class="row m-4 text-center card-body">
    <div class="col ">
      <img class="rounded-circle text-center" src="https://cdn.pixabay.com/photo/2016/06/10/01/05/hotel-room-1447201_960_720.jpg" width="250px" height="250px" alt="">
 
      <a  class="btn btn-secondary border m-3" href="{{path('hotel_chambre')}}">Nos chambres</a>
          </div>
    <div class="col ">
    
    <img class="rounded-circle text-center" src="https://cdn.sortiraparis.com/images/80/1467/388338-tous-au-restaurant-2018-a-paris-ouverture-des-reservations.jpg" width="250px" height="250px" alt="">
        <a class="btn btn-secondary border m-3" href="{{path('hotel_restaurant')}}">Notre restaurant</a>
          </div>
    <div class="col ">
    <img class="rounded-circle " src="https://img.freepik.com/photos-gratuite/beaute-spa_144627-46202.jpg?w=2000" width="250px" height="250px" alt="">
      <a class="btn btn-secondary border m-3" href="{{path('hotel_spa')}}">Notre SPA</a>
      </div>

</body>

{% endblock %}

templates/hotel/propos.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contact{% endblock %}

{% block body %}
<body style= "background-color:#D7CCC8">
<div class="card mb-3">
  <img class="card-img-top" src="https://images.unsplash.com/photo-1541435469116-8ce8ccc4ff85?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTIwfHxob3RlbHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60" height="450px" alt="Card image cap">
  <div class="card-body">
    
  </div>
<h1 class="m-3">Notre Histoire</h1>
<p class="m-3">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nihil unde facilis enim deserunt debitis reprehenderit quia praesentium? Sequi ipsum ab accusamus, natus mollitia est distinctio? Dignissimos voluptatum sit debitis at?
Dolorem ipsa sunt laudantium fugiat assumenda consectetur sapiente sint minima reprehenderit commodi nisi doloremque officiis corrupti soluta sequi temporibus itaque, asperiores labore sit atque eum quaerat consequuntur obcaecati nam? Perspiciatis!</p>

<p class="m-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad incidunt libero, cum hic sed inventore beatae atque a voluptatum, magnam odio similique nobis mollitia deleniti repudiandae illum dolore repellendus voluptatem.
Voluptatibus recusandae iste ipsam ipsa nostrum maiores, quidem quisquam magnam dolorem pariatur facilis sint repudiandae nisi debitis saepe non illum optio, tenetur veniam eligendi placeat sunt amet explicabo. Voluptatibus, vitae!</p>

<h1 class="m-3">Une expérience Unique</h1>
<p class="m-3">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nihil unde facilis enim deserunt debitis reprehenderit quia praesentium? Sequi ipsum ab accusamus, natus mollitia est distinctio? Dignissimos voluptatum sit debitis at?
Dolorem ipsa sunt laudantium fugiat assumenda consectetur sapiente sint minima reprehenderit commodi nisi doloremque officiis corrupti soluta sequi temporibus itaque, asperiores labore sit atque eum quaerat consequuntur obcaecati nam? Perspiciatis!</p>

<p class="m-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad incidunt libero, cum hic sed inventore beatae atque a voluptatum, magnam odio similique nobis mollitia deleniti repudiandae illum dolore repellendus voluptatem.
Voluptatibus recusandae iste ipsam ipsa nostrum maiores, quidem quisquam magnam dolorem pariatur facilis sint repudiandae nisi debitis saepe non illum optio, tenetur veniam eligendi placeat sunt amet explicabo. Voluptatibus, vitae!</p>
<div class="text-center">
<h1 class="m-3 text center">Plan et accès</h1>
  <iframe class=" text-center m-3" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2625.474162345977!2d2.336511!3d48.849168000000006!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e671db9b89a8fd%3A0x667457c0479c7131!2s15%20Rue%20de%20Vaugirard%2C%2075006%20Paris!5e0!3m2!1sfr!2sfr!4v1666345128610!5m2!1sfr!2sfr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>>
  </div>

</body>

{% endblock %}

templates/hotel/resa.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HotelController!
{% endblock %}

{% block body %}
<body style= "background-color:#D7CCC8">
<h1 class="text-center">Nos chambres </h1>

	{% extends 'base.html.twig' %}

{% block title %}Accueil
{% endblock %}

{% block body %}

	<div class="row">
		{% for item in chambre %}
			<div class="col-md-4">
				<div class="card" style="width: 18rem;">
					<img src="{{ item.photo }}" class="card-img-top">
					<div class="card-body">
						<h5 class="card-title">{{ item.titre }}</h5>
						<p class="card-text">{{ item.description|raw }}</p>
						<p class="card-text">{{ item.prix_journalier / 100|number_format(2) }}€</p>
						<a href="{{ path('cart_add', {id: item.id}) }}" class="btn btn-primary">Ajouter au panier</a>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>

{% endblock %}


	</div>
	<div class="col-md-6">
		<div class="card mb-3" style="width: 18rem;">
			<h3 class="card-header">{{ chambre.titre }}</h3>
			<p class="card-text">{{ chambre.description_courte }}</p>
			<img src="{{ chambre.photo }}" alt="Image de la chambre">
			<div class="card-body">
				<p class="card-text">{{ chambre.description_longue }}</p>
				<p class="card-text text-end fw-bold">{{ chambre.prixJournalier }}€/j</p>
			</div>
		</div>
	

		{{ form_start(form) }}

		{{ form_row(form.dateHeureDepart) }}
		{{ form_row(form.dateHeureFin) }}

		<button type="submit" class="btn btn-secondary">Réserver Votre chambre</button>

		{{ form_end(form) }}

	</div>

	<div class="col-md-6">
		<div class="card mb-3" style="width: 18rem;">
			<h3 class="card-header">{{ chambre.titre }}</h3>
			<p class="card-text">{{ chambre.description_courte }}</p>
			<img src="{{ chambre.photo }}" alt="Image de la chambre">
			<div class="card-body">
				<p class="card-text">{{ chambre.description_longue }}</p>
				<p class="card-text text-end fw-bold">{{ chambre.prixJournalier }}€/j</p>
			</div>
		</div>
	

		{{ form_start(form) }}

		{{ form_row(form.dateHeureDepart) }}
		{{ form_row(form.dateHeureFin) }}

		<button type="submit" class="btn btn-secondary">Réserver Votre chambre</button>

		{{ form_end(form) }}
	
	</div>
	



</body>

{% endblock %}

templates/hotel/restaurant.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HotelController!
{% endblock %}

{% block body %}
<body style= "background-color:#D7CCC8">
	<h1 class="text-center m-5">Notre Restaurant </h1>
	<div class="card col-md-5 m-5 d-inline-block" style="width: 18rem;">
  <img class="card-img-top" src="https://images.unsplash.com/photo-1596701062351-8c2c14d1fdd0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjd8fGhvdGVsfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60"  alt="Petit dejeuner">
  <div class="card-body">
    <h5 class="card-title">Petit Déjeuner Continental</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
	<h5 class="card-text">25.00 €</h5>
    <a href="#" class="btn btn-secondary">Notre menu petit dejeuner</a>
  </div>
</div>
<div class="card card col-md-5 m-5 d-inline-block" style="width: 18rem;">
  <img class="card-img-top" src="https://images.unsplash.com/photo-1531088009183-5ff5b7c95f91?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NTF8fGhvdGVsfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60">
  <div class="card-body">
    <h5 class="card-title">Petit Déjeuner healfy</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
	<h5 class="card-text">32.00 €</h5>
    <a href="#" class="btn btn-secondary">Notre menu petit dejeuner</a>
  </div>
</div>
<div class="card card col-md-5 m-5 d-inline-block" style="width: 18rem;">
  <img class="card-img-top" src="https://plus.unsplash.com/premium_photo-1661594716320-e2a76204bf9c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzMxfHxob3RlbHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60" height="400px">
  <div class="card-body">
    <h5 class="card-title"> Déjeuner </h5>
    <p class="card-text">Nos menus dejeuner sont préparés soigneusement par notre chef. les produits sont locaux et suivent la saisonnalité	.</p>
	<h5 class="card-text">60.00 €</h5>
    <a href="#" class="btn btn-secondary">Notre menu déjeuner</a>
  </div>
</div>
<div class="card card col-md-5 m-5 d-inline-block" style="width: 18rem;">
  <img class="card-img-top" src="https://images.unsplash.com/photo-1605880319800-4f524f05436c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NjY2fHxob3RlbHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60" height="400px">
  <div class="card-body">
    <h5 class="card-title"> Diner </h5>
    <p class="card-text">Nos menus du soir sont préparés soigneusement par notre chef. les produits sont locaux et suivent la saisonnalité	.</p>
	<h5 class="card-text">60.00 €</h5>
    <a href="#" class="btn btn-secondary">Notre menu déjeuner</a>
  </div>
</div>
	

</body>
{% endblock %}

templates/hotel/spa.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HotelController!
{% endblock %}

{% block body %}
<body style= "background-color:#D7CCC8">
<h1 class="text-center m-5">Envie de bien-être</h1>
    <h5 class="text-center"> Nous avons ce qu'il vous faut !!! Demander notre brochure à la réception.</h5>
	<div class="card col-md-5 m-5 d-inline-block" style="width: 18rem;">
  <img class="card-img-top" src="https://plus.unsplash.com/premium_photo-1661411524703-f3fb9b48294f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTYzfHxob3RlbHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60" height="430px"  alt="Jaccuzzi">
  <div class="card-body">
    <h5 class="card-title">Jaccuzzi</h5>
    <p class="card-text">Notre hotel dispose d'un Jaccuzzi. Nos professionnels seront la pour vous accompagnés</p>
	<h5 class="card-text">40.00 €</h5>
   
  </div>
</div>
<div class="card card col-md-5 m-5 d-inline-block" style="width: 18rem;">
  <img class="card-img-top" src="https://plus.unsplash.com/premium_photo-1661295619246-1202703df9f7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDI3fHxob3RlbHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60">
  <div class="card-body">
    <h5 class="card-title">Sauna</h5>
    <p class="card-text">Notre hotel dispose d'un Jaccuzzi. Nos professionnels seront la pour vous accompagner.</p>
	<h5 class="card-text">52.00 €</h5>
    
  </div>
</div>
<div class="card card col-md-5 m-5 d-inline-block" style="width: 18rem;">
  <img class="card-img-top" src="https://img.freepik.com/photos-gratuite/beaute-spa_144627-46202.jpg?w=2000" height="430px">
  <div class="card-body">
    <h5 class="card-title"> Nos soins </h5>
    <p class="card-text">Nos professionnels vous proposent une liste de soins, de massages, pour votre bien être</p>
	<h5 class="card-text"> a partir de 90.00 €</h5>
  
  </div>
</div>

	
</body>

{% endblock %}